// clients/app-client-angular/src/lib/components/task-progress/task-progress.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BackgroundTaskService } from '../../background-task.service';

@Component({
  selector: 'PS-task-progress',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="ps-task-progress">
      <div *ngFor="let task of tasks()" class="ps-task-item">
        <div class="ps-task-header">
          <span class="ps-task-type">{{ task.taskType }}</span>
          <span class="ps-task-status">{{ task.status }}</span>
        </div>
        <div *ngIf="task.description" class="ps-task-description">
          {{ task.description }}
        </div>
        <div class="ps-task-progress-bar">
          <div
            class="ps-task-progress-fill"
            [style.width.%]="task.completionPercentage"
          ></div>
        </div>
        <div class="ps-task-percentage">{{ task.completionPercentage }}%</div>
      </div>
    </div>
  `,
})
export class TaskProgressComponent {
  private taskService = inject(BackgroundTaskService);
  tasks = this.taskService.tasks;
}

// clients/app-client-react/src/task-progress.tsx
import { JSX } from 'react';
import type { BackgroundTask } from '@PS/app-client';
import { useBackgroundTasks } from './hooks';

export function TaskProgress(): JSX.Element {
  const { tasks } = useBackgroundTasks();

  return (
    <div className="ps-task-progress">
      {tasks.map((task: BackgroundTask) => (
        <div key={task.id} className="ps-task-item">
          <div className="ps-task-header">
            <span className="ps-task-type">{task.taskType}</span>
            <span className="ps-task-status">{task.status}</span>
          </div>
          {task.description && (
            <div className="ps-task-description">{task.description}</div>
          )}
          <div className="ps-task-progress-bar">
            <div
              className="ps-task-progress-fill"
              style={{ width: `${task.completionPercentage}%` }}
            />
          </div>
          <div className="ps-task-percentage">{task.completionPercentage}%</div>
        </div>
      ))}
    </div>
  );
}
